# Generated by Django 5.1.2 on 2024-11-07 04:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardblockpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('featured_page', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('featured_page', 2)]], {})}),
        ),
    ]
